### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by ghost** [nepphhh/arrasio#12]
How do I use this?

I need to upload files to 2 vps? 1 server for client and 1 for server?

**Comment by bonzibuddy801** [comment]
go here: https://glitch.com/edit/#!/remix/kot32-template-arras

**Comment by ghost** [comment]
@bonzibuddy801 Im trying to install it on my vps. 

Do you know how to do that?

**Comment by bonzibuddy801** [comment]
What is your VPS?

**Comment by ghost** [comment]
@bonzibuddy801 Digital Ocean Ubuntu or I can change it to anything.

**Comment by bonzibuddy801** [comment]
use glitch.com

**Comment by bonzibuddy801** [comment]
what do you mean change?

**Comment by ghost** [comment]
@bonzibuddy801 If I need another OS I can get it. So how do I do this?

**Comment by bonzibuddy801** [comment]
use glitch.com

**Comment by 213zeuse** [comment]
I want a kot32 srever

**Comment by Koleotank** [comment]
i privated my template because of people like you.


please don't act retarded and have a nice day.

**Comment by diep3io** [comment]
213 zeuse i can mmmmake . a  templtes for you :3 cause it has mega ac powerrrr ;3

**Comment by EternalFrostOrig** [comment]
Guys, this is not the place to talk about this take this elsewhere

**Comment by erosramses18** [comment]
why?

**Comment by Colonizor48** [comment]
This is mentally retarded. I think what he is trying to ask is how to put it on a dedicated server. Don't get mad at him. This might be a good way for him to leanr.
