### ISSUE TITLE
Token Required

### ISSUE THREAD

**Issue by 253153** [nepphhh/arrasio#6]
Where do we find the token?

**Comment by polikilopl** [comment]
???

**Comment by 253153** [comment]
<img width="1210" alt="screen shot 2018-06-12 at 5 22 31 pm" src="https://user-images.githubusercontent.com/23563565/41323720-3d2d4ca4-6e65-11e8-9945-0199931d7337.png">

What to fill in for part where it says "Token required."?

**Comment by 253153** [comment]
@nepphhh Can you please let me know what the token is?

**Comment by AC5230** [comment]
I believe we have built in tokens you can change, I think they're in newserver.js and server.js respectively.

**Comment by F0RIS** [comment]
@deniskrop write to me
